apiVersion: v1
kind: ReplicaSet
metadata:
 name: myapp-replicaset
 labels:
   app:myapp
spec:
  selector:
   matchlabels: 
     env:production
  replica: 3
  templates:
    metadata:
      name: nginx-2
      labels:
        env:production
    spec:
      containers:
        - name: nginx
          image: nginx       
  